name: Code checks

on:
  push:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
        with:
          python-version: "3.11"
          enable-cache: "true"

      - name: Ruff format
        run: uvx ruff format --check --diff permutect/

      - name: Ruff check
        run: uvx ruff check permutect/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
        with:
          python-version: "3.11"
          enable-cache: "true"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libhts-dev libdeflate-dev

      - name: Install package
        run: |
          uv pip install --system '.[dev]' \
            --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Run unit tests
        run: pytest permutect/test/utils permutect/test/architecture permutect/test/data -x -v
